INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (1, 'Director', 1);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (2, 'Manager', 2);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (3, 'Lead', 3);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (4, 'Developer', 4);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (5, 'DevOps', 4);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (6, 'QA', 4);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (7, 'Intern', 5);

INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, MANAGER) VALUES (1, 'Thor', 1, NULL );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, MANAGER) VALUES (2, 'Iron Man', 2, 1 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, MANAGER) VALUES (3, 'Hulk', 3, 1 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, MANAGER) VALUES (4, 'Captain America', 2, 1 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, MANAGER) VALUES (5, 'War Machine', 6, 2 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, MANAGER) VALUES (6, 'Vison', 5, 2 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, MANAGER) VALUES (7, 'Falcon', 4, 4 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, MANAGER) VALUES (8, 'AntMan', 3, 4 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, MANAGER) VALUES (9, 'Spider Man', 7, 2 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, MANAGER) VALUES (10, 'Black Widow', 4, 3 );