INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (1, 'Director', 1);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (2, 'Manager', 2);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (3, 'Lead', 3);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (4, 'Developer', 4);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (5, 'DevOps', 4);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (6, 'QA', 4);
INSERT INTO DESIGNATION(ID, TITLE, LEVEL) VALUES (7, 'Intern', 5);

INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, PARENT) VALUES (1, 'EMP1', 1, NULL );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, PARENT) VALUES (2, 'EMP2', 2, 1 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, PARENT) VALUES (3, 'EMP3', 2, 1 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, PARENT) VALUES (4, 'EMP4', 3, 2 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, PARENT) VALUES (5, 'EMP5', 3, 2 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, PARENT) VALUES (6, 'EMP6', 3, 2 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, PARENT) VALUES (7, 'EMP7', 3, 3 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, PARENT) VALUES (8, 'EMP8', 4, 3 );
INSERT INTO EMPLOYEE(ID, NAME, DESIGNATION, PARENT) VALUES (9, 'EMP9', 5, 3 );
