CREATE TABLE EMPLOYEE(
    ID INT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(64) NOT NULL,
    PARENT INT,
    DESIGNATION INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (PARENT) REFERENCES EMPLOYEE(ID)
);
