CREATE TABLE DESIGNATION(
    ID INT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR (64) NOT NULL,
    LEVEL INT NOT NULL
);

CREATE TABLE EMPLOYEE(
    ID INT NOT NULL,
    NAME VARCHAR(64) NOT NULL,
    MANAGER INT,
    DESIGNATION INT,
    PRIMARY KEY (ID),
    FOREIGN KEY (MANAGER) REFERENCES EMPLOYEE(ID),
    FOREIGN KEY (DESIGNATION) REFERENCES DESIGNATION(ID)
);
